[hitran]
git-tree-sha1 = "9fb2bde5493edee9217e83a9847dd2c00b535cfa"

[hitran_molec_id_10_NO2]
git-tree-sha1 = "03b061091250ee05893c1cf7822989fcbc269aca"
lazy = true

    [[hitran_molec_id_10_NO2.download]]
    sha256 = "0178fb2ee4fb5c7d0b65f7ad2b8b1fb7938187fe81f8b539c6cff1bba511382e"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_10_NO2.tar.gz"

[hitran_molec_id_11_NH3]
git-tree-sha1 = "9a2831715959ff19ccb5f86cb568fa69ba0de646"
lazy = true

    [[hitran_molec_id_11_NH3.download]]
    sha256 = "07319d9d6ac712c513b39e90e7ce0f355d4fbb46e608c0c532296bbccde8a1e7"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_11_NH3.tar.gz"

[hitran_molec_id_12_HNO3]
git-tree-sha1 = "87b62a8a207cca3e14ef3e06243641f32dc49889"
lazy = true

    [[hitran_molec_id_12_HNO3.download]]
    sha256 = "c481a452e8402315b45ac43e14721ed35cbd32a1e10a4b4612bdac1d38404f9e"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_12_HNO3.tar.gz"

[hitran_molec_id_13_OH]
git-tree-sha1 = "0a35f9d2ed816dd7c737b69ee365e568219bb9e0"
lazy = true

    [[hitran_molec_id_13_OH.download]]
    sha256 = "fa2c2e36e6b1c1250bb61fe98950c09a559c1d93c11c836d594409da28019980"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_13_OH.tar.gz"

[hitran_molec_id_14_HF]
git-tree-sha1 = "8c985b23504e98a4987169729cf4baff2f446670"
lazy = true

    [[hitran_molec_id_14_HF.download]]
    sha256 = "73838f72f3197f021461cb1494d7c8afc95d8cbc73773b58a7a6e5693afa04cf"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_14_HF.tar.gz"

[hitran_molec_id_15_HCl]
git-tree-sha1 = "0f3910f483ec93c28966af24f8df191273ba42d4"
lazy = true

    [[hitran_molec_id_15_HCl.download]]
    sha256 = "9df08bbe9042134b8ebba8a71f0a1cac16506f53fff259b7213bee5ac1a7f284"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_15_HCl.tar.gz"

[hitran_molec_id_16_HBr]
git-tree-sha1 = "16b122595b8b1f62ad6b6c80afd8883ad4110ccf"
lazy = true

    [[hitran_molec_id_16_HBr.download]]
    sha256 = "5c2af8360ca32dcebf4c17b588b10bea49c19711a87f2e90f5a0f9f13dc3be50"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_16_HBr.tar.gz"

[hitran_molec_id_17_HI]
git-tree-sha1 = "2e90414da959c2ea31e433565d01baa89a966868"
lazy = true

    [[hitran_molec_id_17_HI.download]]
    sha256 = "fbfcf1b95b34eeb98c4b7bcb8f69883ec080be512ab3156b0e4898d2fe960bb6"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_17_HI.tar.gz"

[hitran_molec_id_18_ClO]
git-tree-sha1 = "5a3fa3bf9ed2455573137c3c188beb5b0613af4b"
lazy = true

    [[hitran_molec_id_18_ClO.download]]
    sha256 = "fbf0ed26694b32140175b738be461f9038bc578022c53af7673ad6f6ef3a5f5d"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_18_ClO.tar.gz"

[hitran_molec_id_19_OCS]
git-tree-sha1 = "87d8c6de532d90481a72fe56b0cb0df60032cabc"
lazy = true

    [[hitran_molec_id_19_OCS.download]]
    sha256 = "527801aa16099ea56995c7b958146d60ff1c10ad41de3da35e7dd9c6928ef8c4"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_19_OCS.tar.gz"

[hitran_molec_id_1_H2O]
git-tree-sha1 = "738b53c3ad6f795ebae1f9af6642f7b04efba4d6"
lazy = true

    [[hitran_molec_id_1_H2O.download]]
    sha256 = "207ce6869225e8fb574708ebb776baf1f2bd62280b4ad367965c7e81dde5e92a"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_1_H2O.tar.gz"

[hitran_molec_id_20_H2CO]
git-tree-sha1 = "2d658b942566ff2b763f59e1e1a80f79a9f30855"
lazy = true

    [[hitran_molec_id_20_H2CO.download]]
    sha256 = "0b09941e1ff04310460714550d83da6e1cad948424cf03d81255c15b9469a7a9"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_20_H2CO.tar.gz"

[hitran_molec_id_21_HOCl]
git-tree-sha1 = "a36c6e2ff41ddc34db81ccf04eb4b95c93fd201c"
lazy = true

    [[hitran_molec_id_21_HOCl.download]]
    sha256 = "16f73523ef62c4b905f19daaf1d5689207a1755e8ff1aaf6355de01581d929d3"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_21_HOCl.tar.gz"

[hitran_molec_id_22_N2]
git-tree-sha1 = "5fb2ee8bd79de88bc65d42030ceb34c798be98a3"
lazy = true

    [[hitran_molec_id_22_N2.download]]
    sha256 = "2c93e907b0e6e170d0961280cbe83ae6850770d48ce39f8bfe643c0952417b6c"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_22_N2.tar.gz"

[hitran_molec_id_23_HCN]
git-tree-sha1 = "e9578a691291ad5cd824aa18c169c7583ffe2d79"
lazy = true

    [[hitran_molec_id_23_HCN.download]]
    sha256 = "639f1d901ee4a4469145c60c81f4eb850e55e3ea80cd7e1b3853f38f0aa8fec6"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_23_HCN.tar.gz"

[hitran_molec_id_24_CH3Cl]
git-tree-sha1 = "4a2a3577d2fa112dc6e9098d7b37f2fb84d528ae"
lazy = true

    [[hitran_molec_id_24_CH3Cl.download]]
    sha256 = "b7a0458206d9f3190200dc9f308471a19197b58854fe3dddba85c18afafba04d"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_24_CH3Cl.tar.gz"

[hitran_molec_id_25_H2O2]
git-tree-sha1 = "f0a468afba092cb5c5ba713b30266b9d0b2d2752"
lazy = true

    [[hitran_molec_id_25_H2O2.download]]
    sha256 = "c725327f5c39a1d4e6aa96407a58a1ec1e9ad5678c30d605457a2fc662ad24d4"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_25_H2O2.tar.gz"

[hitran_molec_id_26_C2H2]
git-tree-sha1 = "2f16168d3c88a2e1e27219503cb8c5957e080747"
lazy = true

    [[hitran_molec_id_26_C2H2.download]]
    sha256 = "f2f6fdf571aed0d81f14a0d0670f67182550f1afc05de1b7632e7e6138363e8c"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_26_C2H2.tar.gz"

[hitran_molec_id_27_C2H6]
git-tree-sha1 = "2551c5d408d1ffe0a508cd08cf164aef4028417c"
lazy = true

    [[hitran_molec_id_27_C2H6.download]]
    sha256 = "9f48fd3179ae82c9a399478a9cef1aa7611995bde16d019e4af87ec7fbc0beaa"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_27_C2H6.tar.gz"

[hitran_molec_id_28_PH3]
git-tree-sha1 = "d1fd295fed40b6152aacaa00ec408ecac6dadc68"
lazy = true

    [[hitran_molec_id_28_PH3.download]]
    sha256 = "c6854104ee72a4e2e00493957a18f47945a86104aea2fe0fa1c3f406e4b83871"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_28_PH3.tar.gz"

[hitran_molec_id_29_COF2]
git-tree-sha1 = "e644a7b750124ca52508c461654d09f63c104489"
lazy = true

    [[hitran_molec_id_29_COF2.download]]
    sha256 = "fbae34fe99421b9749c74283265857573682b5ccac89aec189a0dcc2d489a5d3"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_29_COF2.tar.gz"

[hitran_molec_id_2_CO2]
git-tree-sha1 = "bd1208b6552fe1d2c7419043680ba0b7486062a6"
lazy = true

    [[hitran_molec_id_2_CO2.download]]
    sha256 = "53b50dd1586e1af04fe70236608174d9cd20936629c2bc88212097270caca028"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_2_CO2.tar.gz"

[hitran_molec_id_31_H2S]
git-tree-sha1 = "267bcf6a281f0212a15bac1f1b634d6f248fa654"
lazy = true

    [[hitran_molec_id_31_H2S.download]]
    sha256 = "ce5a6ceee7fb0a4dff019b3791f686e5d7a1c0c69212355e9c4202d4f0f94fbd"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_31_H2S.tar.gz"

[hitran_molec_id_32_HCOOH]
git-tree-sha1 = "d4a5073c78ec6b25c8f3bb495e9cc340a84ca8e9"
lazy = true

    [[hitran_molec_id_32_HCOOH.download]]
    sha256 = "e0998df574813e913cd63b0ceb377f21bf22699821d6e34a4df2a6bd4bbb837c"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_32_HCOOH.tar.gz"

[hitran_molec_id_33_HO2]
git-tree-sha1 = "c0e37e9be99645dc33f388b319d1b2c912b16554"
lazy = true

    [[hitran_molec_id_33_HO2.download]]
    sha256 = "d13b780c18af7c278a81c8e6796fcae65887f4c48c09ff8f25cc1a1796fdef6d"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_33_HO2.tar.gz"

[hitran_molec_id_34_O]
git-tree-sha1 = "901406cdf27279622f89a17558b8236015172175"
lazy = true

    [[hitran_molec_id_34_O.download]]
    sha256 = "5dac68e9b3769d5ea9c0bac98e13dd6013ce78598e5e55106237189729971191"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_34_O.tar.gz"

[hitran_molec_id_36_NOp]
git-tree-sha1 = "4a8eb1a14a185eb0e4332f67a55bad708862a705"
lazy = true

    [[hitran_molec_id_36_NOp.download]]
    sha256 = "1aabe4908bb42891b80aa96bac8745ca5a43f4fbf17775c8447deffcb35dd0e4"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_36_NOp.tar.gz"

[hitran_molec_id_37_HOBr]
git-tree-sha1 = "02dce84e305f08bc8580d8f180625cd0694cb65b"
lazy = true

    [[hitran_molec_id_37_HOBr.download]]
    sha256 = "642a3293b3d1af882259d918a41568c226ac977bbb8e0f7b43e80eaaaba55d65"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_37_HOBr.tar.gz"

[hitran_molec_id_38_C2H4]
git-tree-sha1 = "bb4c108ca89ade9a278bf243811026e2b99d35a7"
lazy = true

    [[hitran_molec_id_38_C2H4.download]]
    sha256 = "d69823720b73afe018de97869170a1f5ffed0745e5cd12f5c13fe3ffc99b425c"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_38_C2H4.tar.gz"

[hitran_molec_id_39_CH3OH]
git-tree-sha1 = "b7cf31a2cbae8742d6652e40235c033d8b00dfec"
lazy = true

    [[hitran_molec_id_39_CH3OH.download]]
    sha256 = "c93fae62951f17200914783fd0716b241ad6caad762effb5846b9f7f2ace56c0"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_39_CH3OH.tar.gz"

[hitran_molec_id_3_O3]
git-tree-sha1 = "c2c28f36f479d91e3818d5e9133bcd6cba992bf2"
lazy = true

    [[hitran_molec_id_3_O3.download]]
    sha256 = "f4ffb76d7f213606c8db8e22d83d544e7cf4a5f3b19bbde0f9a2aa7876dad537"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_3_O3.tar.gz"

[hitran_molec_id_40_CH3Br]
git-tree-sha1 = "9da577ecb9a53c507aedb7eb6e447ab469718c7b"
lazy = true

    [[hitran_molec_id_40_CH3Br.download]]
    sha256 = "d1e13677c0b4a4c2cd8afa355249e28b1387b326fa49c8db56609ccb80b70b17"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_40_CH3Br.tar.gz"

[hitran_molec_id_41_CH3CN]
git-tree-sha1 = "164146faf7844be6324cdee00fc5f149c9776e01"
lazy = true

    [[hitran_molec_id_41_CH3CN.download]]
    sha256 = "894fd0ba40a16a8fa8c46720d4ced7c1c1eac4da5015c7925c18cc8bb026b42d"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_41_CH3CN.tar.gz"

[hitran_molec_id_43_C4H2]
git-tree-sha1 = "851b538fc2cf16d17fc559e0e50febc89ba68cfc"
lazy = true

    [[hitran_molec_id_43_C4H2.download]]
    sha256 = "2414563bc8ad93a9414a08bb97bc0d251c80586a28a42d1e0cdaa8c633d33a08"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_43_C4H2.tar.gz"

[hitran_molec_id_44_HC3N]
git-tree-sha1 = "0e552289810c406e0f5a00c6f3a9dc37e7b1c2f7"
lazy = true

    [[hitran_molec_id_44_HC3N.download]]
    sha256 = "43a5edfc8c911eb8230605d2309f3a163fc276df0471ee1924eab8de7287a433"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_44_HC3N.tar.gz"

[hitran_molec_id_45_H2]
git-tree-sha1 = "da9f4c3038a2766afff60efdaf49e15338c3d1aa"
lazy = true

    [[hitran_molec_id_45_H2.download]]
    sha256 = "34f3a9d2eb0be371b7153484d2566259ffa3332b417952033551423942495b32"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_45_H2.tar.gz"

[hitran_molec_id_46_CS]
git-tree-sha1 = "d79651e4e3de5655e185a46114f3abefaf79a1fc"
lazy = true

    [[hitran_molec_id_46_CS.download]]
    sha256 = "a6e5592a76d17115bd28b0fce75adf3dd19df719fdac7cd1d4c64fdad3323686"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_46_CS.tar.gz"

[hitran_molec_id_47_SO3]
git-tree-sha1 = "7735ee9170060c0a18e9eed61144b0c1e824aac6"
lazy = true

    [[hitran_molec_id_47_SO3.download]]
    sha256 = "4466d2fabfdea0f7e96c039b56bf89ceea66da825c991f888f6193b45800e9ae"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_47_SO3.tar.gz"

[hitran_molec_id_48_C2N2]
git-tree-sha1 = "6d25739e73057dc75e51cf5d715a415359da286a"
lazy = true

    [[hitran_molec_id_48_C2N2.download]]
    sha256 = "2879bebc936f1ee0e7a981a3457911d0a7d835fa72bd8705bf885171c93b6d07"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_48_C2N2.tar.gz"

[hitran_molec_id_49_COCl2]
git-tree-sha1 = "e4cef38f7f4aac3a45e3f6a1d38fb186ff16b164"
lazy = true

    [[hitran_molec_id_49_COCl2.download]]
    sha256 = "501f33c8a2667ad0f953f197c4579563233a66e0ca788e3961a3ee7c6bd121ad"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_49_COCl2.tar.gz"

[hitran_molec_id_4_N2O]
git-tree-sha1 = "50cd7506415bf23b906917fb9ffa43a89030f587"
lazy = true

    [[hitran_molec_id_4_N2O.download]]
    sha256 = "79c2708906e45b06c9704649de0cfbebd7e3a684a627dab2b24e9dc257eece9f"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_4_N2O.tar.gz"

[hitran_molec_id_5_CO]
git-tree-sha1 = "36666454592523a1dcb1acc60be2430d0fdfec4e"
lazy = true

    [[hitran_molec_id_5_CO.download]]
    sha256 = "498e469c3b55f679bad84f08b836fd1b69d84ab07726b578f81662fc2f2f1f14"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_5_CO.tar.gz"

[hitran_molec_id_6_CH4]
git-tree-sha1 = "d62e9581682e7b509e6b634e88600746ae37ed67"
lazy = true

    [[hitran_molec_id_6_CH4.download]]
    sha256 = "0b913c86c8cab5027448627e1e3e1c193386ca487ef3148369abe3e7d040f428"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_6_CH4.tar.gz"

[hitran_molec_id_7_O2]
git-tree-sha1 = "50a1eed75de2de99f58510ad8122318dc60b47d1"
lazy = true

    [[hitran_molec_id_7_O2.download]]
    sha256 = "ddfd0e16645ef98976649f9406a929082bf4135c61bb0495c164751c6f3b0ec0"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_7_O2.tar.gz"

[hitran_molec_id_8_NO]
git-tree-sha1 = "dfd98e07e12accacb4977b91922fb4bcf1a6e74a"
lazy = true

    [[hitran_molec_id_8_NO.download]]
    sha256 = "82587d5cca59d7ceb344befed640536831f37c88f4e0d28ae2744de76dbd4c60"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_8_NO.tar.gz"

[hitran_molec_id_9_SO2]
git-tree-sha1 = "1b39a70ddad15a0fb12fc639f7e1e9108d42c518"
lazy = true

    [[hitran_molec_id_9_SO2.download]]
    sha256 = "dc7302251e9aa3347645223945e0213a41014413b5be3ba2adbb6921bf235fda"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/hitran_molec_id_9_SO2.tar.gz"

[solar]
git-tree-sha1 = "78225e93ccd1af9595e693b38b3c1d92d103d17f"
lazy = true

    [[solar.download]]
    sha256 = "981d212afa46750ba6a8e8a1816c60a076e6cbeb71707274387760f9a0f1310c"
    url = "http://web.gps.caltech.edu/~cfranken/hitran_2016/solar_merged_20160127_600_26316_100.out"
