name = "vSmartMOM"
uuid = "7ba11eeb-0a61-4a04-a413-bf612cc2007e"
authors = ["Rupesh Jeyaram <rjeyaram@caltech.edu> and contributors"]
version = "0.5.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Decimals = "abce61dc-4473-55a0-ba07-351d65e31d42"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
InstrumentOperator = "9e589c1b-9e01-4e00-831a-aa39ce86e3ef"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
NetCDF_jll = "7243133f-43d8-5620-bbf4-c2c921802cf3"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CUDA = "3,  4"
CUDAKernels = "0.2, 0.3, 0.4"
DataInterpolations = "3.6"
DiffResults = "1.0"
Distributions = "0.23, 0.24, 0.25"
DocStringExtensions = "0.8"
FastGaussQuadrature = "0.4"
ForwardDiff = "0.10"
Interpolations = "0.12, 0.13"
JLD2 = "0.1, 0.2, 0.3, 0.4"
JSON = "0.21"
KernelAbstractions = "0.6, 0.7,0.8,0.9"
NNlib = "0.8"
NetCDF = "0.10, 0.11"
Parameters = "0.12"
Polynomials = "2"
ProgressMeter = "1.3"
SpecialFunctions = "2"
StaticArrays = "1.2"
StatsBase = "0.33"
TimerOutputs = "0.5"
YAML = "0.4"
julia = "1.6, 1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
