[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FTPClient = "01fcc997-4f28-56b8-8a06-30002c134abb"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
vSmartMOM = "ace8185b-fa20-42f5-912d-1e850dbe6a09"
